// JOGAR UMA FUNÇÃO DENTRO DE UMA VARIÁVEL

let v = function(x) { //CRIOU UMA VARIÁVEL E POS NELA UMA FUNÇÃO DE VALOR X
    return  x*2 //RETORNE X*2
}

console.log(v(5)) //MOSTRE O VALOR DA MULTIPLICAÇÃO USNANDO O NÚMERO COMO PARAMETRO